import React from "react";
import './Privacy.css';

const Privacy = (props) => {

return (
    <>  
        <div className="privacy-root" style={{marginTop: "95px"}}>

            <div className="privacy-content-wrapper">
                <div className="privacy-sqs-layout">
                    <h2>Privacy Policy</h2>
                </div>
            </div>

            <div className="privacy-html-content-wrapper">
                <div className="privacy-sqs-layout">
                    <p className="privacy-sqsrte-large">Thank you for visiting <a className="privacy-sqs-a" target="_blank" href="/">Moksh Art Gallery</a>. We understand and respect your privacy and consider it an important element of our business. This notice describes our privacy policy and broadly pronounces how we handle the information we gather.</p>
                    <ol className="privacy-sqsrte-ol">
                        <li>
                            <p><strong>Background</strong></p>
                            <p><strong>1.1.</strong> This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.  </p>
                            <p><strong>1.2.</strong> This Privacy Policy ("<strong>Privacy Policy</strong>") is published in accordance with: (i) Section 43A of the Information Technology Act, 2000; (ii) Regulation 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal information) Rules, 2011 ("<strong>SPI Rules</strong>"); and (iii) Regulation 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the privacy policy that is applicable in relation to the access or usage of <a target="_blank" className="privacy-sqs-a" href="mokshartgallery.com">mokshartgallery.com</a> ("<strong>Website</strong>").  </p>
                            <p><strong>1.3.</strong> This Privacy Policy covers: (i) the type of information collected from the users through the Website including sensitive personal data or information; (ii) the purpose, means and modes of usage of such information; and (iii) how and to whom such information which has been collected will be disclosed.  </p>
                            <p><strong>1.4.</strong> For the purpose of this Privacy Policy, wherever the context so requires "<strong>You</strong>", "<strong>Your</strong>" or "<strong>User</strong>" shall mean any natural or legal person who uses the Website for availing services offered by the Website ("<strong>Services</strong>"). The terms "<strong>We</strong>", "<strong>Us</strong>", "<strong>Our</strong>" shall mean "<strong>SP</strong>".  </p>
                            <p><strong>1.5.</strong> We reserve the right to make changes to this Privacy Policy at any time. We will provide notice of any significant changes through the Website, or by other means so that you may review the changes before you continue to use the Website. Any such modifications will become effective immediately upon posting to the Website and your continued use of the Website, and/or the Services constitutes your consent to such modifications. If you object to any changes, you may close your account. You agree to periodically review the current version of the Privacy Policy as posted on the Website.  </p>
                        </li>
                        <li>
                            <p><strong>Type of Information Collected from the Customer</strong></p>
                            <p><strong>2.1.</strong> For the purpose of this Privacy Policy, "<strong>Personal Information</strong>" as defined under Section 2(i) of the SPI Rules means, any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available with a body corporate, is capable of identifying such person.  </p>
                            <p><strong>2.2.</strong> "<strong>Sensitive Personal Information</strong>" as defined under Section 3 of the SPI Rules means such personal information which consists of information relating to:</p>
                            <ul>
                                <li>Password</li>
                                <li>Financial information such as Bank Account or Credit Card or Debit Card or other payment instrument details</li>
                                <li>Physical, physiological and mental health condition</li>
                                <li>Sexual orientation</li>
                                <li>Medical records and history</li>
                                <li>Biometric information</li>
                                <li>Any detail relating to the above clauses as provided to body corporate for providing service</li>
                                <li>Any of the information received under above clauses by body corporate for processing, stored or processed under lawful contract or otherwise.  </li>
                            </ul>
                            <p><strong>2.3.</strong> We require Customers who avail our service through the Website to provide us with the following information:</p>
                            <ul>
                                <li>Name of the Customer</li>
                                <li>Email Address</li>
                                <li>Phone Number</li>
                                <li>Address</li>
                                <li>Credit card or debit card information which is required for payment purposes</li>
                                <li>Demographic information such as postcode, preferences and interests</li>
                                <li>All other information as required by Us to provide services to the Customer on the Website.</li>
                            </ul>
                        </li>

                        <li>
                            <p><strong>How the Collected Information will be Used</strong>  </p>
                            <p><strong>3.1.</strong> Sensitive Personal Information and other information collected Clause 2 shall be used in the manner described below:</p>
                            <ul>
                                <li><strong>Registered user name</strong>: The registered user name shall be used to customize the Services availed by the user through the Website and to personalize all communications that are sent to the user by us.</li>
                                <li><strong>Email Address</strong>: Your E-mail address will be used to communicate:<ul>
                                <li>Confirmation of your order booking</li>
                                <li>Details regarding payment for the orders placed</li>
                                <li>Feedback from customers regarding the products and services provided by us</li>
                                <li>Communication of delivery of orders placed by you</li>
                                </ul>
                                </li>
                                <li><strong>Phone Number</strong>: Phone number will be an alternative method to contact the user for any matter related to the services to be availed by you.</li>
                                <li><strong>Address</strong>: The address can either be your residential address or official address or the address of the receiving party to whom the consignment is transported. The same shall be provided to the driver of the vendor carrying the consignment in order to deliver the consignment at the location specified by the user on the Website.</li>
                                <li><strong>Credit Card/Debit Card information</strong>: Credit Card/Debit Card information is used for charging the user for making purchases on the website.  </li>
                            </ul>
                            <p><strong>3.2.</strong> In order to improve the quality of our Services we may ask you to provide us with information regarding your experiences with our products and/or services. Users have the option of choosing not to provide us with this information.  </p>
                            <p><strong>3.3.</strong> We will use your registered account transaction information which includes all information pertaining to your registered account activity, Products ordered, payments made, orders cancelled, modified and the like and communications pertaining to the same in order to assess the credibility of the user.  </p>
                            <p><strong>3.4.</strong> We may use your information to send you promotional information pertaining to the Products and/or Services provided by us.  </p>
                            <p><strong>3.5.</strong> We reserve the right to ask you, at the time of registration with the Website or thereafter, for documentary proof of your identity or other data or postings provided by you with respect to the registration or otherwise. In the event that you fail to provide us with this information or documentary proof, we reserve the right to refuse registration or to terminate your user agreement immediately and cease to provide any Services to you.  </p>
                        </li>

                        <li>
                            <p><strong>Disclosure of Personal Information</strong></p>
                            <p><strong>4.1.</strong> All financial information that is collected through the Website is used solely to bill for the services availed by the user and is not used for marketing or promotional purposes. Towards this end, we disclose such information to a third-party intermediary, for the sole purpose of credit card processing, which is used to make payments to avail of the services on our Website.  </p>
                            <p><strong>4.2.</strong> We may also disclose certain information to third parties solely to help diagnose technical problems, to administer the Website, and improve the quality of the Services provided by us.  </p>
                            <p><strong>4.3.</strong> We reserve the right to disclose any personal information as required by law and when we believe, at our sole discretion that disclosure is necessary to protect our rights, protect someone from injury and/or to comply with a judicial proceeding, court order, or legal process served on our Website  </p>
                        </li>

                        <li>
                            <p><strong>Cookies</strong></p>
                            <p><strong>5.1.</strong> The Website uses temporary cookies, which are files that your web browser puts on your system when you visit a website, to store certain information that is not sensitive personal information. The information collected through these cookies is used by us for the technical administration of the Website, research and development, and to improve the quality of our services. </p>
                            <p><strong>5.2.</strong> We may use third party cookies to track visitor behaviour and to improve the quality of our services. However, such cookies will not store any kind of personal information, nor will such information be disclosed to any third party.  </p>
                            <p><strong>5.3.</strong> These cookies are intended to be automatically cleared or deleted when the User quits the browser application. You are encouraged to use the "<strong>Clear Cookies</strong>" functionality of your browser to ensure such clearing / deletion, since it is impossible for us to guarantee, predict or provide for the behaviour of your system.  </p>
                            <p><strong>5.4.</strong> The information we collect with cookies is not sold, rented, or shared with any third parties.  </p>
                        </li>

                        <li>
                            <p><strong>Third Party Links</strong><br />We may provide links to websites for the convenience and information of users. These websites may not be owned, controlled, or operated by us. In those cases, we cannot control how information collected by those websites will be used, shared, or secured. If the user visits linked sites, we strongly recommend that the user reviews the privacy notices or policies posted at those sites. We are not responsible for the content of linked sites, the user’s use of them, or the information practices of their operators.</p>
                        </li>

                        <li>
                            <p><strong>Security Procedures</strong><br />We have implemented industry standard security policies, rules and technical measures as required under Section 8 of the SPI rules, to protect any kind of personal sensitive information that we have under our control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss.  </p>
                        </li>

                        <li>
                            <p><strong>Choice/Opt-Out</strong></p>
                            <p>If the user wishes to opt- out of receiving non-essential (promotional, marketing-related) communications from us, after setting up an account, they may choose to do so. Further, if a user wishes to remove their contact information from all the Website lists and newsletters, they can do so by unsubscribing from the Website  </p>
                        </li>

                        <li>
                            <p><strong>Grievances</strong></p>
                            <p>If you have any grievances as to the usage of any of your personal information or any other privacy concerns, you can contact the Grievance Officer on <a className="privacy-sqs-a" href="mailto: help@mokshartgallerycom">help@mokshartgallerycom</a> and your grievance will be redressed within a period of 30 (Thirty) days.  </p>
                        </li>

                        <li className="privacy-sqsrte-li">
                            <p><strong>Governing Law and Jurisdiction</strong>  </p>
                            <p>The Privacy Policy shall be governed by and constructed in accordance with the applicable laws of India without reference to conflict of laws principles. Courts in Mumbai, India shall have the exclusive jurisdiction to determine any disputes arising in relation to, or under, this Privacy Policy.</p>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </>
)}

export default Privacy;