import React from "react";
import './Terms.css';

const Terms = (props) => {

return (
    <>  
        <div className="terms-root" style={{marginTop: "95px"}}>

            <div className="terms-content-wrapper">
                <div className="terms-sqs-layout">
                    <h2>Terms of Use</h2>
                </div>
            </div>

            <div className="terms-html-content-wrapper">
                <div className="terms-sqs-layout">
                    <ol className="terms-sqsrte-ol">
                        <li>
                            <p><strong>Background</strong>  </p>
                            <p><strong>1.1.</strong> This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.  </p>
                            <p><strong>1.2.</strong> This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of mokshartgallery.com ("<strong>Website</strong>").  </p>
                            <p><strong>1.3.</strong> The Website is owned, registered and operated by Moksh Art Online ("<strong>Proprietorship</strong>"), Sole Proprietorship having its registered office at 4/A Prem Kutir, 177, Babubhai Chinai Road, Nariman Point, Mumbai 400020.  </p>
                            <p><strong>1.4.</strong> These terms of usage ("<strong>Terms of Use</strong>") govern Your use of the Website and Services (as defined below) provided through the Website. By using or visiting the Website, or by using any content or information provided as part of the Website/Services, you shall be deemed to have read, understood and accepted to be bound by these Terms of Use.  </p>
                            <p><strong>1.5.</strong> For the purpose of these Terms of Use, wherever the context so requires “<strong>You</strong>“, “<strong>Your</strong>” or “<strong>Customer</strong>” or “<strong>User</strong>” shall mean any natural or legal person who uses the Website for availing the Products and Services. The term “<strong>We</strong>”, “<strong>Us</strong>”, “<strong>Our</strong>” shall mean the Proprietorship, its employees, and authorised agents that perform any services on the Proprietorship’s behalf.  </p>
                            <p><strong>1.6.</strong> We reserve the right to make changes to these Terms of Use at any time. Any such modifications will become effective immediately upon posting to the Website and your continued use of the Website, and/or the Services constitutes Your agreement to such modifications. You agree to periodically review the current version of these Terms of Use as posted on the Website.  </p>
                            <p><strong>1.7.</strong> Any Customer who uses or accesses the Website represents to be competent to contract or purchase the Products; and the Vendor, represents and warrants that they have the authority to bind themselves to the Terms of Use.  </p>
                        </li>

                        <li>
                            <p><strong>Services</strong>  </p>
                            <p><strong>2.1.</strong> This website is an Online Marketplace through which we advertise and sell art and artefacts, or any other such products ("<strong>Product(s)</strong>") for our vendor(s), to Customers (as defined below) subject to your compliance with and acceptance of these Terms of Use.  </p>
                            <p><strong>2.2.</strong> For the purposes of these Terms of Use:  </p>
                            <ul>
                                <li>“<strong>Applicable Law</strong>” shall mean any statute, law, regulation, ordinance, rule, judgment, notification, rule of common law, Order, decree, bye-law, government approval, directive, guideline, requirement or other governmental restriction, or any similar form of decision of, or determination by, or any interpretation, policy or administration, having the force of law of any of the foregoing, by any Authority having jurisdiction over the matter in question, whether in effect as of the date of these Terms of Use or thereafter.  </li>
                                <li>“<strong>Authority</strong>” shall mean any national, state, provincial, local or similar government, governmental, regulatory or administrative authority, branch, agency, any statutory body or commission or any non-governmental regulatory or administrative authority, body or other organization to the extent that the rules, regulations and standards, requirements, procedures or Orders of such authority, body or other organization that have the force of Applicable Law or any court, tribunal, arbitral or judicial body in India.  </li>
                                <li>“<strong>Customer</strong>” shall mean any natural or legal person who uses the website to purchase the Products that are being sold by the Vendor on the Website.  </li>
                                <li>“<strong>Vendor</strong>” shall mean any natural or legal person who uses the Website to market and sell the Products to the Customers.  </li>
                            </ul>
                        </li>

                        <li>
                            <p><strong>Platform for Customers</strong>. </p>
                            <p><strong>3.1.</strong> This Website acts as a facilitator between the Vendor and Customer for the purchase of Products. A Customer may purchase Products on the Website without mandatorily registering on the Website, by providing the relevant details as necessitated. However, in order to gain access to our exclusive Product listings, the Customers must register themselves on the Website ("<strong>Registered Customer(s)</strong>"). Such Registered Customer’s details may be verified by the Website by a detailed process which may even include a detailed telephonic conversation between the Website and the Registered Customer. Every Registered Customer shall allocate themselves a unique identification user name and password ("<strong>User ID</strong>” and “<strong>Password</strong>").
                            If You use the Website as Registered Customer, You are responsible for maintaining the confidentiality of Your User ID and Password. You are responsible for all activities that occur under Your User ID and Password.
                            You (whether or not a Registered Customer) agree, inter alia, to provide true, accurate, current and complete information about yourself as prompted by the Website registration form. If You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, We reserve the right to indefinitely suspend, terminate or block/ refuse to provide You with access to the Website.  </p>
                            <p><strong>3.2.</strong> We are solely a facilitator and only enabling the transaction between the Vendors and Customers for the purchase of Products.  </p>
                            <p><strong>3.3.</strong> We do not make any representation or warranty as to the specifics of the Products proposed to be sold or offered to be sold or purchased on the Website. We do not accept liability for any errors or omissions, whether on behalf of itself or third parties.  </p>
                            <p><strong>3.4.</strong> The Website is only a platform that can be utilized by Vendor(s) to gain access to Customer base to market and sell their Products, and for the Customers to gain access to curated Products being sold by the Vendors. At no time shall the Website hold any right, title or interest over the products nor shall it have any obligations or liabilities in respect of such contract.  </p>
                        </li>

                        <li>
                            <p><strong>Representations, Warranties and Obligations of the Website</strong></p>
                            <p>We hereby represent and warrant that (a) We are a Sole Proprietorship (b) We are in compliance with the Applicable Law to provide Services, subject to these Terms of Use; (c) We will comply with the Privacy Policy and ensure data security of the Users at all times  </p>
                        </li>

                        <li>
                            <p><strong>Representations, Warranties and Obligations of the Customer</strong>  </p>
                            <p>The Customer hereby represents and warrants that (a) You are a natural or legal person, competent to contract, and have read, understood and agreed to be bound by these Terms of Use; (b) They shall provide accurate information and details at the time of registration; (c) They shall not default in making payments for Products bought through the Website; (d) They agree and acknowledge the fact that there shall be minor differences between the Product image and the Product in physical form; (e) They shall not demand for refund/ replacement of the Product for such minor variations; and (f) They agree and acknowledge that once the order has been placed on the Website for a Product, they shall not be allowed to cancel or modify the order.  </p>
                        </li>

                        <li>
                            <p><strong>Intellectual Property Rights</strong></p>
                            <p><strong>6.1.</strong> Copyright </p>
                            <p><strong>6.1.1.</strong> The copyrights, design rights (whether or not registered), moral rights, performance rights, database rights, new media rights, names, logos, publicity rights, and any and all other intellectual property and proprietary rights of any nature whatsoever that subsist, or may subsist, or be capable of registration, in each case in relation to the creative work of the Vendor, for all the Products listed on the website rests with the Vendor. The Vendor hereby grants the Proprietorship a royalty-free, non-exclusive, worldwide, perpetual, irrevocable right and license to use, display, the creative works of the Vendor for the purpose of sale of the Product and promotion of the Website/ Proprietorship.  </p>
                            <p><strong>6.1.2.</strong> All Proprietorship’s content included on the Website, including but not limited to, text, graphics, logos, designs, photographs, button icons, images, video clips, digital downloads, data compilations etc., is Our property and is protected by the Applicable Laws with respect to intellectual property rights. The compilation of all content on this Website is Our exclusive property, and shall not be reproduced or used without express written permission from Us. We reserve the right to terminate our engagement with You, if We, in Our sole and absolute discretion, believe that You are in violation of this clause.  </p>
                            <p><strong>6.1.3.</strong> The content made available on or via the Website, is provided to You ‘AS IS’ for Your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without Our prior written consent. We reserve all rights, not expressly granted in and to the Website.  </p>
                            <p><strong>6.2.</strong> Trademarks
                            mokshartgallery.com is the domain of the Proprietorship. The Website, including, but not limited to its graphics, logos, page headers, button icons, scripts and service names constitute trade dress of the Proprietorship. The trademarks, domain names and trade dress of the Proprietorship shall not be used or reproduced without prior written approval from the Proprietorship and may not be used in connection with any Product or Service that is not affiliated with the Sole Proprietorship.  </p>
                            <p><strong>6.3.</strong> License and Warranty for Your Submissions to the Website. </p>
                            <p><strong>6.3.1.</strong> Any information You submit to Us, is at Your own risk. By providing information to Us, You represent and warrant that You are entitled to submit it and that it is not confidential and it is not in violation of any law, contractual restrictions or other third party rights (including any intellectual property rights).  </p>
                        </li>

                        <li>
                            <p><strong>Links</strong>  </p>
                            <p><strong>7.1.</strong> The Website may contain links to other websites ("**Linked Sites“). The Linked Sites are not under the control of the Website. We are not responsible for the content of any Linked Site, including, without limitation to, any link contained in a Linked Site, or any changes or updates to a Linked Site.  </p>
                            <p><strong>7.2.</strong> We are not responsible for any form of transmission, whatsoever, received by the User from any Linked Site. We are providing these links only for convenience, and the inclusion of any such link does not imply endorsement by the Website, of the Linked Sites or any association with its operators or owners including the legal heirs or assigns thereof.  </p>
                            <p><strong>7.3.</strong> On accessing the Linked Sites, You shall be governed by the terms of use, privacy policy and such other additional policies of the Linked Sites. You further acknowledge and agree that We shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, advertising, products, services or other materials available on or through any Linked Sites or for any errors, defamatory content, libel, slander, omissions, falsehoods, obscene content, pornographic material, or any profanity contained therein.  </p>
                        </li>

                        <li>
                            <p><strong>Payment Terms</strong>. </p>
                            <p><strong>8.1.</strong> The Customer on placing an order on the Website, shall be directed to a third party payment gateway ("<strong>Third Party Payment Gateway</strong>"). The Customer shall make payments for Products purchased through the Website through Credit Card/Debit Card or any other method provided by the Third-Party Payment Gateway.</p>
                            <p><strong>8.2.</strong> The Customer agrees and accepts that all nuances and modalities relating to making payment using Third Party Payment Gateway shall be separately governed by arrangement(s) / terms and conditions between You and the relevant banks/ Third Party Payment Gateway. We shall not be responsible, in any manner whatsoever, for any liability that may arise in relation to the payments made through Third Party Payment Gateway.  </p>
                            <p><strong>8.3.</strong> While availing any of the payment method(s) available on the Website, We will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to (a) Lack of authorization for any transactions; (b) Any payment issues arising out of the transaction or (c) Decline of such transaction for any reason.  </p>
                            <p><strong>8.4.</strong> You understand, accept and agree that the payment facility provided Us, is neither a banking nor financial service but is merely a facilitator providing an automated online electronic payment, collection and remittance facility for the transactions between the Customer and Vendor on the Website using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing a payment facility, We are neither acting as trustees nor acting in any fiduciary capacity with respect to the payments made by the Customer against the purchase of Products on the Website.  </p>
                            <p><strong>8.5.</strong> The Website reserves the right to refuse, to process any request for Service availed by a User with a prior history of questionable charges including without limitation, breach of any agreements by such User with Us, or breach/violation of any Applicable Law.  </p>
                            <p><strong>8.6.</strong> You understand, accept and agree that all payments made by the Customer shall be to the Proprietorship based on the invoicing of the Proprietorship to the Customer.  </p>
                            <p><strong>8.7.</strong> Any Goods &amp; Services Tax, or any other applicable taxes, or any changes thereof or any new taxes introduced shall be borne by the Customer.  </p>
                        </li>

                        <li>
                            <p><strong>Modification and Cancellation / Refund and Replacement</strong>.</p>
                            <p><strong>9.1.</strong> No request for modification or cancellation of purchase/booking shall be entertained by the Website.  </p>
                            <p><strong>9.2.</strong> All requests for refund or replacement shall be subject to a final decision made by the Proprietorship.  </p>
                            <p><strong>9.3.</strong> If the order is requested for refund, after payment has been processed, and if the refund is approved by the Proprietorship, the said amount will be refunded within a period of 45 (Forty-Five) days through electronic payment.  </p>
                        </li>

                        <li>
                            <p><strong>Privacy</strong></p>
                            <p>The Website collects, stores, processes and uses Your information in accordance with Website’s Privacy Policy. By using the Website and/ or by providing Your information, You consent to the collection and use of the information You disclose on the Website in accordance with Website’s Privacy Policy.</p>
                        </li>

                        <li>
                            <p><strong>Fraud and Improper Conduct</strong></p>
                            <p><strong>11.1.</strong> You may only access the Website and use the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all provisions of Applicable Law pertaining to Your use of the Services. You agree that You will not in any way:  </p>
                            <ul>
                                <li>Interfere with the ability of others to access or use the Services.</li>
                                <li>Disrupt the normal flow of communication or otherwise act in a manner that adversely affects other Users ability to use the Website or the Services.  </li>
                                <li>Interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Services.  </li>
                                <li>Upload or post or use the Service to transfer, any content or other material that contains or constitutes viruses, Trojan horse or other code with malicious, disruptive and/or destructive features.</li>
                                <li>You shall not attempt to gain unauthorized access to the account of any other User, or otherwise interfere with any other User’s use of the Service.  </li>
                                <li>You shall not use any false or misleading information (e.g., false or misleading names, email addresses or URLs) when using the service, including, without limitation, with respect to any identifying information for Your account, and all information that You provide must be accurate and correct, and You must update any changes to such information, so that it remains current.  </li>
                            </ul>
                        </li>

                        <li>
                            <p><strong>Limitation and Disclaimer of Warranty</strong></p>
                            <p><strong>12.1.</strong> The Website, the Services and each portion thereof are provided “AS IS” without warranties of any kind either express or implied. To the fullest extent possible pursuant to Applicable Law, We disclaim all warranties, express or implied, with respect to the Website, the Services and each portion thereof, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or other violation of rights.  </p>
                            <p><strong>12.2.</strong> We shall not be liable for any loss or damages suffered by the Customer due to any failure on the part of Vendor to supply the Product for any reason whatsoever, including but not limited to, partial or total damaged Product, incorrect Product, or other circumstances which may or may not be within the control of the Vendor.  </p>
                            <p><strong>12.3.</strong> We shall not be liable for any direct, indirect, incidental or consequential damages, whatsoever incurred by the User due to use of the Website’s Services or due to the non- availability of the Website Services.  </p>
                            <p><strong>12.4.</strong> If You are dissatisfied or harmed by this Website or anything related with the Website, Your sole remedy shall be to terminate these Terms of Use by unsubscribing on the Website.  </p>
                            <p><strong>12.5.</strong> We shall be entitled to disclose to the Authority, as required by Applicable Law or by any directive or request from any government body, the particulars of the User engaged with the Website.  </p>
                            <p><strong>12.6.</strong> We shall be entitled to add, to vary or amend any or all these terms and conditions at any time and the User shall be bound by such addition, variation or amendment once such addition, variation or amendment is incorporated into these terms and conditions, and such amended terms and conditions are on the Website.  </p>
                        </li>

                        <li>
                            <p><strong>Indemnification</strong>. 
                            You undertake to indemnify Us, for any losses or damages resulting from any third party claims or complaints arising from, or in connection with Your actions on the Website, and/or breach of this Agreement.</p>
                        </li>

                        <li>
                            <p><strong>Termination</strong>. </p>
                            <p><strong>14.1.</strong> We may terminate these Terms of Use with respect to You, immediately without notice in the event of any breach by You of these Terms of Use or any of our applicable policies, as posted on the Website from time to time or upon a misuse of the Services by You.  </p>
                            <p><strong>14.2.</strong> You agree that upon the termination of these Terms of Use, We may delete all information related to You with respect to the Services availed by You. Further, You will no longer be able to log into the Website.  </p>
                        </li>

                        <li>
                            <p><strong>Severability</strong>. </p>
                            <p>If any part of the Terms of Use are determined to be invalid or unenforceable pursuant to Applicable Laws, including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use for Services shall continue in effect.  </p>
                        </li>

                        <li>
                            <p><strong>General</strong></p>
                            <p>Unless otherwise specified herein, these Terms of Use for Services and the Privacy Policy (provided on the Website) constitutes the entire agreement between You and the Website, in respect of the Services and supersedes all previous written and oral agreements between You and the Website, if any. Our failure to act with respect to a breach by You or others does not waive Our right to act with respect to subsequent or similar breaches.  </p>
                        </li>

                        <li>
                            <p><strong>Governing Law and Dispute Resolution</strong></p>
                            <p>These Terms of Use and the relationship between the Parties hereto shall be governed by, and interpreted in accordance with, the laws of India without having regard to the conflict of laws provisions thereunder. The courts of Mumbai, Maharashtra, India shall have exclusive jurisdiction over all disputes arising pursuant to these Terms of Use.</p>
                        </li>

                        <li className="terms-sqsrte-li">
                            <p><strong>Grievance Officer</strong></p>
                            <p>In accordance with Information Technology Act 2000 and rules made there under, the contact details of the Grievance Officer are: Email - <a className="privacy-sqs-a" href="mailto: help@mokshartgallery.com">help@mokshartgallery.com</a>.</p>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </>
)}

export default Terms;